const FETCH_DIRECTORY_START = 'FETCH_DIRECTORY_START';
const FETCH_DIRECTORY_SUCCESS = 'FETCH_DIRECTORY_SUCCESS';
const FETCH_DIRECTORY_FAILURE = 'FETCH_DIRECTORY_FAILURE';

export {
	FETCH_DIRECTORY_START,
	FETCH_DIRECTORY_SUCCESS,
	FETCH_DIRECTORY_FAILURE,
};
